name: Creating AWS named profile
description: OIDC AWS role to be used as AWS profile

inputs:
  role-to-assume:
    description: ARN of the IAM Role to assume
    required: true
  profile:
    description: AWS profile name to create 
    required: true
  region:
    description: AWS region to use 
    required: true

runs:
  using: "composite"
  steps:
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    id: creds
    with:
      role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
      aws-region: ${{ env.AWS_REGION }}
      output-credentials: true
      unset-current-credentials: true
    env:
      AWS_REGION: ${{ inputs.region }}
      AWS_ROLE_TO_ASSUME: ${{ inputs.role-to-assume }}

  - name: Setup AWS Profile
    run: |
      aws configure set region ${{ env.AWS_REGION }} --profile ${{ env.AWS_PROFILE }}
      aws configure set aws_access_key_id ${{ steps.creds.outputs.aws-access-key-id }} --profile ${{ env.AWS_PROFILE }}
      aws configure set aws_secret_access_key ${{ steps.creds.outputs.aws-secret-access-key }} --profile ${{ env.AWS_PROFILE }}
      aws configure set aws_session_token ${{ steps.creds.outputs.aws-session-token }} --profile ${{ env.AWS_PROFILE }}
    shell: bash
    env:
      AWS_REGION: ${{ inputs.region }}
      AWS_PROFILE: ${{ inputs.profile }}

  - name: Unset AWS variables
    run: |
      echo "AWS_ACCESS_KEY_ID=" >> $GITHUB_ENV
      echo "AWS_SECRET_ACCESS_KEY=" >> $GITHUB_ENV
      echo "AWS_SESSION_TOKEN=" >> $GITHUB_ENV
    shell: bash

  - name: Verify AWS profile
    run: aws sts get-caller-identity --profile ${{ env.AWS_PROFILE }}
    shell: bash
    env:
      AWS_PROFILE: ${{ inputs.profile }}

outputs:
  aws-account-id:
    description: AWS Account ID
    value: ${{ steps.creds.outputs.aws-account-id }}
  aws-access-key-id:
    description: AWS Access Key ID
    value: ${{ steps.creds.outputs.aws-access-key-id }}
  aws-secret-access-key:
    description: AWS Secret Key
    value: ${{ steps.creds.outputs.aws-secret-access-key }}
  aws-session-token:
    description: AWS Session Token
    value: ${{ steps.creds.outputs.aws-session-token }}